### ISSUE TITLE
Doesn't open browser on OSX Lion with Sublime Build 2200

### ISSUE THREAD

**Issue by maxim** [a1fred/SublimeGoogle#2]
Tried your plugin first time, the idea is great, but pressing enter on a search result prints "I've opened web browser for this page" on the bottom line, but doesn't actually do anything. I use chrome beta builds but also have Safari installed (non-default). Would be great to have it working.

**Comment by a1fred** [comment]
Hmm. Any messages in console (Ctrl-`)?

**Comment by a1fred** [comment]
Closing due inactivity
